"use strict"

const langauges_data = [
  {
    full_name: "JavaScript",
    folder_name: "javascript",
    hilighter_name: "javascript",
    file_extension: "js",
    problems_solved: 0,
    kyu: 3,
  },
  {
    full_name: "TypeScript",
    folder_name: "typescript",
    hilighter_name: "typescript",
    file_extension: "ts",
    problems_solved: 0,
    kyu: 7,
  },
  {
    full_name: "Python",
    folder_name: "python",
    hilighter_name: "python",
    file_extension: "py",
    problems_solved: 0,
    kyu: 6,
  },
  {
    full_name: "Java",
    folder_name: "java",
    hilighter_name: "java",
    file_extension: "java",
    problems_solved: 0,
    kyu: 7,
  },
  {
    full_name: "PHP",
    folder_name: "php",
    hilighter_name: "php",
    file_extension: "php",
    problems_solved: 0,
    kyu: 5,
  },
  {
    full_name: "SQL",
    folder_name: "sql",
    hilighter_name: "sql",
    file_extension: "sql",
    problems_solved: 0,
    kyu: 8,
  },
  {
    full_name: "Ruby",
    folder_name: "ruby",
    hilighter_name: "ruby",
    file_extension: "rb",
    problems_solved: 0,
    kyu: 8,
  },
  {
    full_name: "Rust",
    folder_name: "rust",
    hilighter_name: "rust",
    file_extension: "rs",
    problems_solved: 0,
    kyu: 8,
  },
  {
    full_name: "C++",
    folder_name: "cpp",
    hilighter_name: "cpp",
    file_extension: "cpp",
    problems_solved: 0,
    kyu: 8,
  },
  {
    full_name: "C#",
    folder_name: "csharp",
    hilighter_name: "csharp",
    file_extension: "cs",
    problems_solved: 0,
    kyu: 8,
  },
  {
    full_name: "C",
    folder_name: "c",
    hilighter_name: "c",
    file_extension: "c",
    problems_solved: 0,
    kyu: 8,
  },
  {
    full_name: "NASM",
    folder_name: "nasm",
    hilighter_name: "x86asm",
    file_extension: "asm",
    problems_solved: 0,
    kyu: 8,
  },
  {
    full_name: "Kotlin",
    folder_name: "kotlin",
    hilighter_name: "kotlin",
    file_extension: "kt",
    problems_solved: 0,
    kyu: 8,
  },
  {
    full_name: "Haskell",
    folder_name: "haskell",
    hilighter_name: "haskell",
    file_extension: "hs",
    problems_solved: 0,
    kyu: 8,
  },
  {
    full_name: "Prolog",
    folder_name: "prolog",
    hilighter_name: "prolog",
    file_extension: "pl",
    problems_solved: 0,
    kyu: 8,
  },
]
